#! /bin/bash
#-p <port> -o <origin> -n <name> -u <username> -i <keyfile>


allHosts=(ec2-54-85-32-37.compute-1.amazonaws.com
ec2-54-193-70-31.us-west-1.compute.amazonaws.com
ec2-52-38-67-246.us-west-2.compute.amazonaws.com
ec2-52-51-20-200.eu-west-1.compute.amazonaws.com
ec2-52-29-65-165.eu-central-1.compute.amazonaws.com
ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com
ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com
ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com
ec2-54-233-185-94.sa-east-1.compute.amazonaws.com)

while getopts "p:o:u:n:i:" argv
do
    case $argv in
        p)
            port=$OPTARG
            ;;
        o)
            origin=$OPTARG
            ;;
        u)
            username=$OPTARG
            ;;
        n)
            name=$OPTARG
            ;;
        i)
            keyfile=$OPTARG
            ;;
        esac
done


#echo "Starting HTTP Server adn other Scripts on EC2 hosts"
for host in "${allHosts[@]}"
do
    echo "Start HTTP Server on $host"

    ssh -i $keyfile $username@$host "nohup python ActiveMeasurement.py 58793 > /dev/null 2>&1 &"
    ssh -i $keyfile $username@$host "nohup ./httpserver -p $port  -n $origin > /dev/null 2>&1 &"
done


echo "Starting DNS Server"
ssh -i $keyfile $username@cs5700cdnproject.ccs.neu.edu  "./dnsserver -p $port -n $name > /dev/null 2>&1 &"

echo "Completed"

#./runCDN -p 44000 -o Orig -n www.example.com -u raghu147 -i ~/.ssh/id_dsa
# DNS dig @129.10.117.186 -p 44000 cs5700cdn.example.com