#! /bin/bash

#-p <port> -o <origin> -n <name> -u <username> -i <keyfile>


allHosts=(ec2-54-85-32-37.compute-1.amazonaws.com
ec2-54-193-70-31.us-west-1.compute.amazonaws.com
ec2-52-38-67-246.us-west-2.compute.amazonaws.com
ec2-52-51-20-200.eu-west-1.compute.amazonaws.com
ec2-52-29-65-165.eu-central-1.compute.amazonaws.com
ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com
ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com
ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com
ec2-54-233-185-94.sa-east-1.compute.amazonaws.com)


while getopts "p:o:u:n:i:" argv
do
    case $argv in
        u)
            username=$OPTARG
            ;;
        i)
            keyfile=$OPTARG
            ;;
        esac
done



for host in "${allHosts[@]}"
do
    echo "Stopping CDN Processes on " $host
    ssh -i $keyfile  $username@$host "killall -9 -u $username python"
done


echo "Stopping DNS Server on cs5700cdnproject.ccs.neu.edu"
ssh -i $keyfile $username@cs5700cdnproject.ccs.neu.edu "killall -9 -u $username python"

echo 'Completed'

#./stopCDN -p 44000 -o Orig -n www.example.com -u raghu147 -i ~/.ssh/id_dsa