#! /bin/bash
# Deploy CDN Script copies all necessary files to every EC2 host and gives them correct permissions

# Use as :  -p <port> -o <origin> -n <name> -u <username> -i <keyfile>


allHosts=(ec2-54-85-32-37.compute-1.amazonaws.com
ec2-54-193-70-31.us-west-1.compute.amazonaws.com
ec2-52-38-67-246.us-west-2.compute.amazonaws.com
ec2-52-51-20-200.eu-west-1.compute.amazonaws.com
ec2-52-29-65-165.eu-central-1.compute.amazonaws.com
ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com
ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com
ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com
ec2-54-233-185-94.sa-east-1.compute.amazonaws.com)


while getopts "p:o:u:n:i:" argv
do
    case $argv in

        p)
            port=$OPTARG
            ;;
        o)
            origin=$OPTARG
            ;;
        u)
            username=$OPTARG
            ;;
        n)
            name=$OPTARG
            ;;
        i)
            keyfile=$OPTARG
            ;;
        esac
done


#echo "Deploying Active Measurement Scripts onto EC2 Machines"
for host in "${allHosts[@]}"
do
    echo "Copying files onto $host"

    scp -i $keyfile ActiveMeasurement.py $username@$host:~/

    scp -i $keyfile httpserver_backup.py $username@$host:~/
    scp -i $keyfile httpserver $username@$host:~/

    ssh -i $keyfile $username@$host "chmod +x httpserver"
    ssh -i $keyfile $username@$host "chmod +x httpserver_backup.py; mkdir -p cache"
    ssh -i $keyfile $username@$host "chmod +x ActiveMeasurement.py"

done



#echo "Deploying onto DNS Server"

scp -i $keyfile dnsserver $username@cs5700cdnproject.ccs.neu.edu:~/
scp -i $keyfile DNSServer.py $username@cs5700cdnproject.ccs.neu.edu:~/
scp -i $keyfile Client.py $username@cs5700cdnproject.ccs.neu.edu:~/
ssh -i $keyfile $username@cs5700cdnproject.ccs.neu.edu "chmod +x ~/dnsserver ; chmod +x ~/DNSServer.py;chmod +x ~/Client.py"

echo 'Completed'


# Script command
#./deployCDN -p 44000 -o Orig -n www.example.com -u raghu147 -i ~/.ssh/id_dsa